apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  labels:
    job: lot-transmitter
  name: lot-transmitter
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      activeDeadlineSeconds: 50
      template:
        metadata:
          labels:
            job: lot-transmitter
        spec:
          containers:
            - name: fpm
              image: ${PHP_IMAGE}:${COMMIT_HASH}
              imagePullPolicy: IfNotPresent
              env:
                - name: SENTRY_PROJECT_ID
                  value: "${SENTRY_PROJECT_ID}"
                - name: SENTRY_PUBLIC_KEY
                  value: "${SENTRY_PUBLIC_KEY}"
                - name: LOGGER_PATH
                  value: "php://stdout"
                - name: S3_BUCKET
                  value: "${S3_BUCKET}"
                - name: S3_PREFIX
                  value: "${S3_PREFIX}"
                - name: AWS_VERSION
                  value: "${AWS_VERSION}"
                - name: AWS_REGION
                  value: "${AWS_REGION}"
                - name: ENVIRONMENT
                  value: "${ENVIRONMENT}"
                - name: COMMIT_HASH
                  value: "${COMMIT_HASH}"
                - name: REST_ENDPOINT_URL
                  value: "${REST_ENDPOINT_URL}"
                - name: JIRA_ENABLE
                  value: "${JIRA_ENABLE}"
                - name: JIRA_ENABLE_CREATE_TICKET
                  value: "${JIRA_ENABLE_CREATE_TICKET}"
                - name: JIRA_HOST
                  value: "${JIRA_HOST}"
                - name: JIRA_USERNAME
                  value: "${JIRA_USERNAME}"
                - name: JIRA_PASSWORD
                  value: "${JIRA_PASSWORD}"
                - name: JIRA_PROJECT
                  value: "${JIRA_PROJECT}"
                - name: JIRA_ISSUETYPE
                  value: "${JIRA_ISSUETYPE}"
              resources:
                limits:
                  memory: 300Mi
                  cpu: 500m
                requests:
                  memory: 300Mi
                  cpu: 500m
              command:
                - /bin/sh
                - -c
                - "sleep 10 && php index.php"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: privatrepo-registry