apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: debug
  name: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      service: debug
  template:
    metadata:
      labels:
        service: debug
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: fpm
          image: ${PHP_IMAGE}:${COMMIT_HASH}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
          env:
            - name: SENTRY_PROJECT_ID
              value: "${SENTRY_PROJECT_ID}"
            - name: SENTRY_PUBLIC_KEY
              value: "${SENTRY_PUBLIC_KEY}"
            - name: LOGGER_PATH
              value: "php://stdout"
            - name: S3_BUCKET
              value: "${S3_BUCKET}"
            - name: S3_PREFIX
              value: "${S3_PREFIX}"
            - name: AWS_VERSION
              value: "${AWS_VERSION}"
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: ENVIRONMENT
              value: "${ENVIRONMENT}"
            - name: COMMIT_HASH
              value: "${COMMIT_HASH}"
            - name: REST_ENDPOINT_URL
              value: "${REST_ENDPOINT_URL}"
            - name: JIRA_ENABLE
              value: "${JIRA_ENABLE}"
            - name: JIRA_ENABLE_CREATE_TICKET
              value: "${JIRA_ENABLE_CREATE_TICKET}"
            - name: JIRA_HOST
              value: "${JIRA_HOST}"
            - name: JIRA_USERNAME
              value: "${JIRA_USERNAME}"
            - name: JIRA_PASSWORD
              value: "${JIRA_PASSWORD}"
            - name: JIRA_PROJECT
              value: "${JIRA_PROJECT}"
            - name: JIRA_ISSUETYPE
              value: "${JIRA_ISSUETYPE}"
          resources:
            limits:
              memory: 300Mi
              cpu: 500m
            requests:
              memory: 300Mi
              cpu: 500m
          ports:
            - containerPort: 9000
              protocol: TCP
      imagePullSecrets:
        - name: privatrepo-registry
